language: node_js
node_js:
  - '8.10.0'
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master
